const strings = {
  es: {
    login: 'Iniciar sesión',
    register: 'Registrarse',
    email: 'Correo electrónico',
    password: 'Contraseña',
    name: 'Nombre completo',
    phone: 'Número de celular',
    whereTo: '¿A dónde vas?',
    origin: 'Origen',
    destination: 'Destino',
    requestRide: 'Solicitar viaje',
    selectVehicle: 'Selecciona un vehículo',
    confirmRide: 'Confirmar viaje',
    driverOnWay: 'Conductor en camino',
    driverArrived: '¡Conductor llegó!',
    finishTrip: 'Finalizar viaje',
    tripHistory: 'Historial de viajes',
    noTrips: 'No tienes viajes aún',
    profile: 'Mi perfil',
    saveChanges: 'Guardar cambios',
    logout: 'Cerrar sesión',
  },
  en: {
    login: 'Log In',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Full name',
    phone: 'Phone number',
    whereTo: 'Where to?',
    origin: 'Origin',
    destination: 'Destination',
    requestRide: 'Request Ride',
    selectVehicle: 'Select a vehicle',
    confirmRide: 'Confirm ride',
    driverOnWay: 'Driver on the way',
    driverArrived: 'Driver arrived!',
    finishTrip: 'Finish trip',
    tripHistory: 'Trip History',
    noTrips: 'No trips yet',
    profile: 'My Profile',
    saveChanges: 'Save changes',
    logout: 'Log out',
  },
};

export default strings;